---
#without this the upgrade fails with:
#  The deploymentconfigs "postgresql" is invalid: metadata.resourceVersion: Invalid value: 0x0: must be specified for an update
- name: Delete annotation from postgresql deploymentconfig
  shell: oc annotate deploymentconfig postgresql -n {{ enmasse_namespace }} kubectl.kubernetes.io/last-applied-configuration-

- name: Install EnMasse
  import_tasks: main.yml

- name: "Postgresql update the imagestreams"
  shell: oc import-image {{ enmasse_postgresql_image }} -n openshift
  register: result
  until: result.stdout
  retries: 75
  delay: 1
  failed_when: not result.stdout

- name: Wait for AMQ rollouts to complete
  import_tasks: wait_for_rollouts.yml
  vars:
    namespace_to_watch: "{{ enmasse_namespace }}"
    rollouts_to_watch:
      - deployment/service-broker
      - deployment/address-space-controller
      - deployment/enmasse-operator
      - deployment/console
      - deployment/keycloak

# Does not seem to exist in 1.5
- name: Delete service account api-server 
  shell: oc delete sa api-server -n {{ enmasse_namespace }}
  failed_when: false

# Does exist in 1.5
- name: Delete 
  shell: oc delete clusterrolebinding enmasse.io:api-server-openshift-enmasse
  failed_when: false

# Does exist in 1.5
- name: Delete 
  shell: oc delete clusterrole enmasse.io:api-server
  failed_when: false

# Does not seem to exist in 1.5
- name: Delete 
  shell: oc delete rolebinding api-server -n {{ enmasse_namespace }}
  failed_when: false

# Does not seem to exist in 1.5
- name: Delete 
  shell: oc delete role enmasse.io:api-server -n {{ enmasse_namespace }}
  failed_when: false
