---
- name: Patch blackbox targets
  include_role:
    name: middleware_monitoring_config
    tasks_from: create_blackboxtargets.yml

- name: Remove console-proxy route
  shell: "oc delete route console-proxy -n {{ enmasse_namespace }}"
  failed_when: false