---
- name: Remove the Fuse Managed namespace
  shell: oc delete project {{ fuse_namespace }}
  failed_when: false

- name: Delete Fuse roles
  shell: oc delete role role-binder -n {{ fuse_namespace }}
  failed_when: false

## Ensure fuse binary is removed after installation
- name: Remove fuse binary
  file:
      path: "{{ item }}"
      state: absent
  with_items:
    - "/tmp/fuse-binary-archive"
    - "/tmp/fuse-binary"