---
- name: template Camel/Fuse orders API
  template:
    src: camel_orders_api.yml
    dest: /tmp/camel_orders_api.yml
  
- name: Add crud Camel/Fuse order API app to the catalog
  command: oc apply -f /tmp/camel_orders_api.yml -n openshift
  register: out
  failed_when: out.stderr != '' and 'Warning' not in out.stderr
