---
# ADDS CRUD SPRING BOOT EXAMPLE APP TO THE CATALOG
- name: template crud spring boot example app
  template:
    src: crud_spboot_example.yml
    dest: /tmp/crud_spboot_example.yml
    
- name: Add crud spring boot example app to the catalog
  command: oc apply -f /tmp/crud_spboot_example.yml -n openshift
  register: out
  failed_when: out.stderr != '' and 'Warning' not in out.stderr
