---
# ADDS LOCATION SOAP APP TO THE CATALOG
- name: location soap app
  template:
    src: location_soap.yml
    dest: /tmp/location.yml
  
- name: Add location soap app to the catalog
  command: oc apply -f /tmp/location.yml -n openshift
  register: out
  failed_when: out.stderr != '' and 'AlreadyExists' not in out.stderr
