---
- name: template Node.js Order Entry UI
  template:
    src: nodejs_order_entry_ui.yml
    dest: /tmp/nodejs_order_entry_ui.yml

- name: newer version of the work_queue_nodejs
  command: oc apply -f /tmp/nodejs_order_entry_ui.yml -n openshift
  register: out
  failed_when: out.stderr != '' and 'Warning' not in out.stderr
