---
- name: template Node.js Order Entry UI
  template:
    src: nodejs_order_entry_ui.yml
    dest: /tmp/nodejs_order_entry_ui.yml

- name: newer version of the work_queue_nodejs
  command: oc apply -f /tmp/nodejs_order_entry_ui.yml -n openshift
  register: out
  until: '"created" in out.stdout or "configured" in out.stdout or "unchanged" in out.stdout or "AlreadyExists" in out.stderr or "Warning" in out.stderr'
  retries: 200
  delay: 5
  failed_when: out.stderr != '' and 'AlreadyExists' not in out.stderr and 'Warning' not in out.stderr
