---
- name: template Node.js Orders Management UI
  template:
    src: nodejs_orders_management_ui.yml
    dest: /tmp/nodejs_orders_management_ui.yml
  
- name: adds a nodejs based UI that renders data from the camel_orders_api template
  command: oc apply -f /tmp/nodejs_orders_management_ui.yml -n openshift
  register: out
  failed_when: out.stderr != '' and 'AlreadyExists' not in out.stderr
