---
- name: Update {{ customise_web_console.configmap_name }} configmap
  import_tasks: install.yml

- name: Get web console pod name
  shell: oc get pods -o jsonpath='{.items[0].metadata.name}' -n {{ customise_web_console.namespace }}
  register: web_console_pod_name

- name: Delete web console pod
  shell: oc delete pod {{ web_console_pod_name.stdout }} -n {{ customise_web_console.namespace }}

- name: Redeploy {{ customise_web_console.app_name }}
  shell: oc rollout status deployment/{{ customise_web_console.app_name }} -n {{ customise_web_console.namespace }}
  register: rollout_cmd
  failed_when: rollout_cmd.rc != 0
  changed_when: rollout_cmd.rc == 0
